name: CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456789012
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
    
    runs-on: ubuntu-latest

    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola, mundo!"

      - name: "Mostrar variables de entorno"
        run: |
         echo "Plataforma: ${{ env.platform }}"
         echo "Región: ${{ env.region }}"
         echo "Cuenta: ${{ env.account }}"
         echo "Usuario: ${{ env.username }}"
         echo "Contraseña: ${{ env.password }}"

      - name: "Mostrando valores por defecto"
        run: 
          echo "event ${{toJSON(github.event)}}"